import { createHash } from "node:crypto";
import type { ComposeOutputInput, ComposeResult, ComposedOutput, FragmentProvenance, LocalFragment } from "./types.js";

export const RENDERER_VERSION = "2";
export const GENERATED_NOTICE = "<!-- Generated by agents.md. Edit configured local files instead. -->";

export function sha256(value: Buffer | string): string {
  return `sha256:${createHash("sha256").update(value).digest("hex")}`;
}

function normalizeMarkdown(value: Buffer | string): string {
  return (Buffer.isBuffer(value) ? value.toString("utf8") : value)
    .replaceAll("\r\n", "\n")
    .replaceAll("\r", "\n")
    .replace(/\n+$/u, "");
}

function fragmentSet(fragments: FragmentProvenance[]): string {
  return [...new Set(fragments.map((fragment) => fragment.fragmentId))].sort().join("\0");
}

function deduplicateFragments(fragments: FragmentProvenance[]): FragmentProvenance[] {
  const groups = new Map<string, FragmentProvenance[]>();
  for (const fragment of fragments) {
    const groupKey = `${fragment.identity}\0${fragment.alias}`;
    const group = groups.get(groupKey) ?? [];
    group.push(fragment);
    groups.set(groupKey, group);
  }
  const allowed = new Map<string, string>();
  for (const [groupKey, group] of groups) {
    const identity = group[0].identity;
    const set = fragmentSet(group);
    const previous = allowed.get(identity);
    if (previous !== undefined && previous !== set) {
      throw new Error(`Conflicting fragment selections for source identity ${identity}`);
    }
    allowed.set(identity, set);
  }
  const seen = new Set<string>();
  const output: FragmentProvenance[] = [];
  for (const fragment of fragments) {
    const key = `${fragment.identity}\0${fragment.fragmentId}`;
    if (seen.has(key)) continue;
    seen.add(key);
    output.push(fragment);
  }
  return output;
}

export function composeOutput(input: ComposeOutputInput): ComposedOutput {
  const fragments = deduplicateFragments(input.fragments);
  const sections: string[] = [GENERATED_NOTICE];
  const owners: string[] = [];
  for (const fragment of fragments) {
    const body = normalizeMarkdown(fragment.body);
    sections.push(`## ${fragment.label}\n\n${body}`);
    owners.push(`${fragment.identity}/${fragment.fragmentId}`);
  }
  for (const local of input.local) {
    const body = normalizeMarkdown(local.body);
    if (body.length === 0) continue;
    sections.push(`## Local: ${local.path}\n\n${body}`);
    owners.push(`local:${local.path}`);
  }
  const body = `${sections.join("\n\n")}\n`;
  return { directory: input.directory, body: Buffer.from(body, "utf8"), fragmentOwners: owners };
}

export function compose(inputs: ComposeOutputInput[]): ComposeResult {
  return { outputs: inputs.map(composeOutput), diagnostics: [] };
}

export function renderClaudeAdapter(): Buffer {
  return Buffer.from("@AGENTS.md\n", "utf8");
}

export function normalizeLocalFragment(path: string, body: Buffer): LocalFragment {
  return { path, body };
}
